### ISSUE TITLE
i have a Issues about get_redis_connection, please help me, 3q

### ISSUE THREAD

**Issue by zenglcGit** [uptick/django-cq#10]
python3.6.1
django-redis 4.8.0

my jangoProject setting.py:
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
            'expiry': 1800,
            'channel_capacity': {
                'cq-tasks': 1000
            }
        },
        'ROUTING': 'example_channels.routing.channel_routing',
    }
}

when i run PublishCurrentTestCase , error happened

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cq\tests\test_base.py", line 433, in test_publish
    backend.clear_current()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cq\backends.py", line 93, in clear_current
    with redis_connection() as conn:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cq\utils.py", line 40, in redis_connection
    conn = get_redis_connection()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_redis\__init__.py", line 17, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature

**Comment by zenglcGit** [comment]
I know why, in the settings file, should add CACHES
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

**Comment by furious-luke** [comment]
Hi there, sorry for the delay in responding!

Hmm, you should only need to have the cache set to Redis when using `django_redis_channel_layer`. Are you able to provide me with a full `settings.py` for debugging?
